wait until connect

diff --git a/bin/rdocker b/bin/rdocker
--- a/bin/rdocker
+++ b/bin/rdocker
@@ -50,9 +50,10 @@ if [ ${CLOSE_CONNECTION} == 1 ]; then
 fi
 
 if [ "$(uname)" == 'Darwin' ]; then
-    PREFIX="export DOCKER_HOST=tcp://127.0.0.1:"
+    PREFIX_HOSTNAME_ONLY="tcp://127.0.0.1:"
+    PREFIX="export DOCKER_HOST=${PREFIX_HOSTNAME_ONLY}"
     if [ $FLAG_HOSTNAME_ONLY = 1 ]; then
-        PREFIX="tcp://127.0.0.1:"
+        PREFIX=${PREFIX_HOSTNAME_ONLY}
     fi
 
     if [ "`docker ps -aq --filter name=${CONTAINER_NAME} 2> /dev/null`" != "" ]; then
@@ -104,9 +105,10 @@ elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
     
     NEW_DOCKER_HOST=${SOCK_DIR}/${1}.sock
     
-    PREFIX="export DOCKER_HOST=unix://"
+    PREFIX_HOSTNAME_ONLY="unix://"
+    PREFIX="export DOCKER_HOST=${PREFIX_HOSTNAME_ONLY}"
     if [ $FLAG_HOSTNAME_ONLY = 1 ]; then
-        PREFIX="unix://"
+        PREFIX=${PREFIX_HOSTNAME_ONLY}
     fi
 
     if [ -e ${NEW_DOCKER_HOST} ]; then
@@ -148,5 +150,11 @@ else
   exit 1
 fi
 
+for i in {1..60} ; do
+    docker -H ${PREFIX_HOSTNAME_ONLY}${NEW_DOCKER_HOST} info &> /dev/null
+    if [ $? = 0 ] ; then break; fi
+    if [ $i = 10 ] ; then echo "could not connect to ${1}" >&2 ; exit 1; fi
+    sleep 1
+done
 
 echo "${PREFIX}${NEW_DOCKER_HOST}"
